import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Kuca from '../components/Kuca'
import { useStateContext } from '../context/StateContext'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

export default function Home({proizvodi}) {
  const {products,setproducts} = useStateContext()
  useEffect(() => {
    setproducts(proizvodi)
  }, [])
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Kuca />
      <Footer />

    </div>
  )
}

export async function getServerSideProps() {
  const products = await fetch('http://localhost:3000/api/products')
  
  return {
    props: { proizvodi: await products.json() }
  }
}
